#ifndef _SECONDARY_DRIVER_DEFS_
#define _SECONDARY_DRIVER_DEFS_

#define SECONDARY_SIOCTL_TYPE 40000

#define SECONDARY_IOCTL_COMMAND_1  (CTL_CODE( SECONDARY_SIOCTL_TYPE, 0x901, METHOD_IN_DIRECT, FILE_ANY_ACCESS  ))
#define SECONDARY_IOCTL_COMMAND_2  (CTL_CODE( SECONDARY_SIOCTL_TYPE, 0x902, METHOD_IN_DIRECT, FILE_ANY_ACCESS  ))


#define SECONDARY_DEVICE_NAME             L"SecondaryDriver"
#define SECONDARY_KERNEL_DEVICE_NAME      L"\\Device\\" ## SECONDARY_DEVICE_NAME

#endif
