#ifndef _COMM_SHARED_DEFS_
#define _COMM_SHARED_DEFS_

#define COMM_QUEUE_IOCTL_MSG_UM_TO_KM_DIRECT       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8B0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define COMM_QUEUE_IOCTL_INVERTED_CALL_GET_MESSAGE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8B1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define COMM_QUEUE_IOCTL_INVERTED_CALL_REPLY       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8B2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define COMM_QUEUE_MIN_MESSAGE_SIZE     32
#define COMM_QUEUE_MAX_MESSAGE_SIZE     (128 * 1024)

#pragma pack(push, 8)
typedef struct _COMM_MESSSAGE_HEADER
{
    __int32          MessageCode;
    unsigned __int32 MessageStatus;
}COMM_MESSSAGE_HEADER, * PCOMM_MESSSAGE_HEADER;

typedef struct _COMM_INVERTED_HEADER
{
    unsigned __int64 Sequence;
    unsigned __int32 Status;
    unsigned __int32 ReplySize;
}COMM_INVERTED_HEADER, * PCOMM_INVERTED_HEADER;



#endif